In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression ## linear regression model
from sklearn.metrics import mean_absolute_error ## metric to find out any model's accuracy
from sklearn.svm import LinearSVR ## another Regression model we can use pt 2
from sklearn.svm import SVR ## another Regression model we can use pt.3
from sklearn.ensemble import RandomForestRegressor ## another Regression model we can use pt 4
from sklearn.model_selection import cross_val_score ## cross validation score
import joblib                                       ## to export a model

In [2]:
train_set=pd.read_csv('final_train_set.csv')
test_set=pd.read_csv('final_test_set.csv')
test_set_actual=pd.read_csv('test.csv')

In [3]:
X_train,y_train=train_set.drop('SalePrice',axis=1),train_set[['SalePrice']].to_numpy().flatten()

In [4]:
X_train

MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0           60.0         65.0   8450.0          7.0          5.0     2003.0   
1           20.0         80.0   9600.0          6.0          8.0     1976.0   
2           60.0         68.0  11250.0          7.0          5.0     2001.0   
3           70.0         60.0   9550.0          7.0          5.0     1915.0   
4           60.0         84.0  14260.0          8.0          5.0     2000.0   
...          ...          ...      ...          ...          ...        ...   
1455        60.0         62.0   7917.0          6.0          5.0     1999.0   
1456        20.0         85.0  13175.0          6.0          6.0     1978.0   
1457        70.0         66.0   9042.0          7.0          9.0     1941.0   
1458        20.0         68.0   9717.0          5.0          6.0     1950.0   
1459        20.0         75.0   9937.0          5.0          6.0     1965.0   

      YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  ...  SaleType_ConLw  \
0           2003.0       196.0       706.0         0.0  ...             0.0   
1           1976.0         0.0       978.0         0.0  ...             0.0   
2           2002.0       162.0       486.0         0.0  ...             0.0   
3           1970.0         0.0       216.0         0.0  ...             0.0   
4           2000.0       350.0       655.0         0.0  ...             0.0   
...            ...         ...         ...         ...  ...             ...   
1455        2000.0         0.0         0.0         0.0  ...             0.0   
1456        1988.0       119.0       790.0       163.0  ...             0.0   
1457        2006.0         0.0       275.0         0.0  ...             0.0   
1458        1996.0         0.0        49.0      1029.0  ...             0.0   
1459        1965.0         0.0       830.0       290.0  ...             0.0   

      SaleType_New  SaleType_Oth  SaleType_WD  SaleCondition_Abnorml  \
0              0.0           0.0          1.0                    0.0   
1              0.0           0.0          1.0                    0.0   
2              0.0           0.0          1.0                    0.0   
3              0.0           0.0          1.0                    1.0   
4              0.0           0.0          1.0                    0.0   
...            ...           ...          ...                    ...   
1455           0.0           0.0          1.0                    0.0   
1456           0.0           0.0          1.0                    0.0   
1457           0.0           0.0          1.0                    0.0   
1458           0.0           0.0          1.0                    0.0   
1459           0.0           0.0          1.0                    0.0   

      SaleCondition_AdjLand  SaleCondition_Alloca  SaleCondition_Family  \
0                       0.0                   0.0                   0.0   
1                       0.0                   0.0                   0.0   
2                       0.0                   0.0                   0.0   
3                       0.0                   0.0                   0.0   
4                       0.0                   0.0                   0.0   
...                     ...                   ...                   ...   
1455                    0.0                   0.0                   0.0   
1456                    0.0                   0.0                   0.0   
1457                    0.0                   0.0                   0.0   
1458                    0.0                   0.0                   0.0   
1459                    0.0                   0.0                   0.0   

      SaleCondition_Normal  SaleCondition_Partial  
0                      1.0                    0.0  
1                      1.0                    0.0  
2                      1.0                    0.0  
3                      0.0                    0.0  
4                      1.0                    0.0  
...                    ...    

In [5]:
y_train

array([208500., 181500., 223500., ..., 266500., 142125., 147500.])

# Linear Regression Model

In [6]:
## 1st model using LinearRegression
linear_model=LinearRegression()

In [7]:
linear_model.fit(X_train,y_train)

LinearRegression()

In [8]:
y_linear_predicted=linear_model.predict(X_train)

In [9]:
y_linear_predicted

array([208541.82623178, 205564.78540582, 205374.87520883, ...,
       275419.98534338, 141488.94167508, 149073.22041806])

In [10]:
mean_absolute_error(y_train,y_linear_predicted)

13223.676215904054

In [11]:
linear_scores=cross_val_score(linear_model,X_train,y_train,scoring='neg_mean_squared_error',cv=10)

In [12]:
linear_scores

array([-5.71285829e+08, -1.20680339e+09, -5.50726808e+08, -1.72054080e+09,
       -9.16074525e+08, -1.94746256e+09, -5.90114420e+08, -5.17889238e+08,
       -4.52906284e+09, -1.16805508e+10])

In [13]:
np.sqrt(-linear_scores).mean()

42040.878091097446

In [14]:
y_linear_predicted=linear_model.predict(test_set)

In [15]:
y_linear_predicted

array([112578.43674876, 159150.48353728, 186307.35012957, ...,
       179206.07785421, 114926.39228157, 223195.95322299])

In [16]:
pd.DataFrame(y_linear_predicted,columns=['SalePrice'])

SalePrice
0     112578.436749
1     159150.483537
2     186307.350130
3     196793.307868
4     205368.704295
...             ...
1454   84246.140415
1455   79792.033586
1456  179206.077854
1457  114926.392282
1458  223195.953223

[1459 rows x 1 columns]

In [17]:
test_set_actual=pd.read_csv('test.csv')

In [18]:
y_linear_predicted_df=pd.DataFrame(test_set_actual['Id'])
y_linear_predicted_df['SalePrice']=y_linear_predicted

In [19]:
y_linear_predicted_df

Id      SalePrice
0     1461  112578.436749
1     1462  159150.483537
2     1463  186307.350130
3     1464  196793.307868
4     1465  205368.704295
...    ...            ...
1454  2915   84246.140415
1455  2916   79792.033586
1456  2917  179206.077854
1457  2918  114926.392282
1458  2919  223195.953223

[1459 rows x 2 columns]

In [20]:
y_linear_predicted_df.to_csv('y_linear_predicted.csv',index=False)

# Random Forest Regressor Model

In [21]:
forest_reg=RandomForestRegressor()

In [22]:
forest_reg.fit(X_train,y_train)

RandomForestRegressor()

In [23]:
reg_scores=cross_val_score(forest_reg,X_train,y_train,scoring='neg_mean_squared_error',cv=10)

In [24]:
reg_scores

array([-6.15817830e+08, -6.92343425e+08, -4.88995624e+08, -1.46146097e+09,
       -1.07833414e+09, -6.91600186e+08, -5.46876135e+08, -5.80502041e+08,
       -1.66227339e+09, -7.46090963e+08])

In [25]:
np.sqrt(-reg_scores).mean()

28617.13379596162

In [26]:
y_random_predicted=forest_reg.predict(test_set)

In [27]:
pd.DataFrame(y_random_predicted,columns=['SalePrice'])

SalePrice
0     126571.50
1     150372.50
2     182975.51
3     181608.32
4     196473.27
...         ...
1454   88414.50
1455   85869.00
1456  154646.09
1457  110509.75
1458  227996.16

[1459 rows x 1 columns]

In [28]:
y_random_predicted_df=pd.DataFrame(test_set_actual['Id'])
y_random_predicted_df['SalePrice']=y_random_predicted

In [29]:
y_random_predicted_df.to_csv('y_random_predicted.csv',index=False)

# Linear Support Vector Machine Regressor (Linear SVR)

In [30]:
linear_svr_model=LinearSVR()

In [31]:
linear_svr_model.fit(X_train,y_train)

/home/harshkulkarni/venv/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVR()

In [32]:
y_svr_linear_predicted=linear_svr_model.predict(X_train)

In [33]:
mean_absolute_error(y_train,y_svr_linear_predicted)

23607.68811087901

In [34]:
y_linear_svr_predicted=linear_svr_model.predict(test_set)

In [35]:
pd.DataFrame(y_linear_svr_predicted,columns=['SalePrice'])

SalePrice
0     132080.075030
1     189582.152890
2     208439.512090
3     205737.916673
4     180604.375975
...             ...
1454   83593.293234
1455   99331.376538
1456  199525.673436
1457  127931.685251
1458  242751.119814

[1459 rows x 1 columns]

In [36]:
y_linear_svr_predicted_df=pd.DataFrame(test_set_actual['Id'])
y_linear_svr_predicted_df['SalePrice']=y_linear_svr_predicted

In [37]:
y_linear_svr_predicted_df.to_csv('y_linear_svr_predicted.csv',index=False)

# SVR Model

In [38]:
svr_model=SVR()

In [39]:
svr_model.fit(X_train,y_train)

SVR()

In [40]:
y_svr_predicted=svr_model.predict(X_train)

In [41]:
mean_absolute_error(y_train,y_svr_predicted)

55517.86505947624

In [42]:
y_svr_predicted=svr_model.predict(test_set)

In [43]:
pd.DataFrame(y_svr_predicted,columns=['SalePrice'])

SalePrice
0     163010.582654
1     163029.098774
2     163041.139724
3     162993.066536
4     162937.501079
...             ...
1454  162915.446949
1455  162915.419234
1456  163088.175268
1457  162995.211821
1458  162991.033536

[1459 rows x 1 columns]

In [44]:
y_svr_predicted_df=pd.DataFrame(test_set_actual['Id'])
y_svr_predicted_df['SalePrice']=y_svr_predicted

In [45]:
y_svr_predicted_df.to_csv('y_svr_predicted.csv',index=False)

# The End